apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-kv-provider
  namespace: three-tier
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "7a655473-eb2d-4c58-909f-47ffcee4e658"

    keyvaultName: "kv-helm-poc-rs01"

    tenantId: "3c6c5376-23f5-4364-a594-2c6614a80703"

    objects: |
      array:
        - |
          objectName: postgres-username
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-dbname
          objectType: secret