apiVersion: v1
kind: ServiceAccount

metadata:
  name: backend-sa
  
  annotations:
    azure.workload.identity/client-id: "7a655473-eb2d-4c58-909f-47ffcee4e658"
    azure.workload.identity/tenant-id: "3c6c5376-23f5-4364-a594-2c6614a80703"