{{- if .Values.enabled }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: backend-sa
      automountServiceAccountToken: true

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgres-kv-provider
      
      containers:
      - name: backend

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true

        command:
        - sh
        - -c
        - "while true; do echo Backend Running; sleep 30; done"

        env:
        - name: DB_HOST
          value: postgres-service

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname

        ports:
        - containerPort: 3000

{{- end }}